import { complain, inform } from '../actions/logging';
import { defaults } from '../config';

import path = require('path');
import { ensureFileIsPresent } from '../actions/files';
const javaHome = require('java-home'); // tslint:disable-line:no-var-requires

export const command = 'run';

export const desc = 'Aggregates the reports generated by Serenity BDD and produces a HTML report';

export const builder = {
    cacheDir:        {
        default:  defaults.cacheDir,
        describe: 'An absolute or relative path to where the Serenity BDD Reporter jar should be stored',
    },
    destination:     {
        default:  defaults.reportDir,
        describe: 'Directory to contain the generated Serenity BDD report',
    },
    features:        {
        default:  defaults.featuresDir,
        describe: 'Source directory containing the Cucumber.js feature files',
    },
    source:          {
        default:  defaults.sourceDir,
        describe: 'Source directory containing the Serenity BDD JSON output files',
    },
    issueTrackerUrl: {
        describe: 'Base URL for issue trackers other than JIRA',
    },
    jiraProject:     {
        describe: 'JIRA project identifier',
    },
    jiraUrl:         {
        describe: 'Base URL of your JIRA server',
    },
    project:         {
        describe: 'Project name to appear in the Serenity reports (defaults to the project directory name)',
    },
};

export const handler = (argv: any) =>
    findJava()
        .then(inform('Using Java at: %s'));

// --

const findJava = () =>
    javaHome.getPath()
        .then(javaDir => ensureFileIsPresent(path.resolve(javaDir, 'bin/java')))
        .catch(complain('Is JAVA_HOME configured correctly? %s'));
